//! Recorded chair-output regression corpus.
//!
//! Every recorded grok-4.3 canary-chair `directive_proposal_v1` fence must pass
//! the directive validator. The corpus under `tests/fixtures/grok_chair/*.fence.txt`
//! is generated by `tests/fixtures/grok_chair/generate.sh` using the canary
//! cabinet; this test then runs offline. It proves that the Grok chair reliably
//! emits fences accepted by the closed-keyset and verb-allowlist validator.

use council_rs::engine::directive_fence::validate_directive_proposal_v1;
use std::fs;
use std::path::Path;

#[test]
fn grok_chair_fixture_all_pass() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/grok_chair");
    let mut fences: Vec<_> = fs::read_dir(&dir)
        .expect("grok_chair fixture dir must exist")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| {
            p.file_name()
                .is_some_and(|n| n.to_string_lossy().ends_with(".fence.txt"))
        })
        .collect();
    fences.sort();

    assert!(
        fences.len() >= 20,
        "the regression corpus requires >=20 recorded grok-chair fences, found {} \
         (regenerate with tests/fixtures/grok_chair/generate.sh)",
        fences.len()
    );

    let mut failures = Vec::new();
    for f in &fences {
        let body = fs::read_to_string(f).expect("read fence fixture");
        if let Err(e) = validate_directive_proposal_v1(&body) {
            failures.push(format!("  {}: {e}", f.display()));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} grok-chair fences failed directive validation:\n{}",
        failures.len(),
        fences.len(),
        failures.join("\n")
    );
}

/// The corpus guards the triage seat preamble's verdict distribution. Without
/// a threshold assertion, a model bump or preamble
/// edit silently regresses to all-Dismiss with zero test failures. We assert the
/// three unambiguous buckets and deliberately leave the four MEDIUM-urgency rows
/// (03,06,07,08) as a graded judgment zone — they may legitimately move either way.
///   HIGH-urgency real conditions (01,02,04,05,09) -> Act  (5/5)
///   LOW-urgency weak signals      (10..16)          -> Dismiss (7/7)
///   boot probes                   (17..20)          -> Dismiss (4/4)
#[test]
fn grok_chair_fixture_verdict_distribution() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/grok_chair");

    // The recorded fences are raw chair output in a ```json ... ``` markdown block.
    // Pull the JSON out of the fence the same
    // way the D2 validator does before parsing the verdict.
    let extract_json = |body: &str| -> String {
        let mut out = String::new();
        let mut inside = false;
        for line in body.lines() {
            // Match the validator's extract_single_json_fence rules exactly:
            // open on a line whose trim is *exactly* "```json", close on the next
            // line whose trim is *exactly* "```". Avoids drifting on ```jsonc /
            // ```text info strings or a ``` appearing inside prose.
            if !inside {
                if line.trim() == "```json" {
                    inside = true;
                }
                continue;
            }
            if line.trim() == "```" {
                break;
            }
            out.push_str(line);
            out.push('\n');
        }
        out
    };

    let verdict = |stem: &str| -> String {
        let body = fs::read_to_string(dir.join(format!("{stem}.fence.txt")))
            .unwrap_or_else(|_| panic!("fence {stem} must exist"));
        let json = extract_json(&body);
        let v: serde_json::Value =
            serde_json::from_str(&json).unwrap_or_else(|e| panic!("fence {stem} not JSON: {e}"));
        v["verdict"]
            .as_str()
            .unwrap_or_else(|| panic!("fence {stem} has no string verdict"))
            .to_string()
    };

    let must_act = ["01", "02", "04", "05", "09"];
    let must_dismiss = [
        "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
    ];

    for s in must_act {
        assert_eq!(
            verdict(s),
            "Act",
            "HIGH-urgency escalation {s} must yield Act; triage Act path regressed (re-run \
             generate.sh and inspect the seat preamble)"
        );
    }
    for s in must_dismiss {
        assert_eq!(
            verdict(s),
            "Dismiss",
            "weak/boot escalation {s} must yield Dismiss; triage is over-firing on low-evidence \
             signals (the preamble lost its symmetry)"
        );
    }
}
