#!/usr/bin/env python3
"""Probe NVIDIA NIM: list /v1/models then try chat on each.

Writes:
  - stdout summary
  - council-rs/config/nim-invokable-allowlist.txt (unless --no-write)
  - optional markdown report via --report PATH

Requires NVIDIA_API_KEY in the environment.
"""
from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import sys
import time
import urllib.error
import urllib.request
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ALLOWLIST = ROOT / "council-rs" / "config" / "nim-invokable-allowlist.txt"
NIM_BASE = "https://integrate.api.nvidia.com/v1"


def list_models(key: str) -> list[str]:
    req = urllib.request.Request(
        f"{NIM_BASE}/models",
        headers={"Authorization": f"Bearer {key}"},
    )
    with urllib.request.urlopen(req, timeout=45) as r:
        data = json.loads(r.read().decode())
    return sorted({m.get("id", "") for m in data.get("data", []) if m.get("id")})


def probe_chat(key: str, model: str) -> tuple[str, str, float, str]:
    body = json.dumps(
        {
            "model": model,
            "messages": [{"role": "user", "content": "Reply with exactly: ACK"}],
            "max_tokens": 8,
            "temperature": 0,
        }
    ).encode()
    req = urllib.request.Request(
        f"{NIM_BASE}/chat/completions",
        data=body,
        headers={
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    t0 = time.time()
    try:
        with urllib.request.urlopen(req, timeout=45) as r:
            raw = r.read().decode()
            j = json.loads(raw)
            txt = ((j.get("choices") or [{}])[0].get("message") or {}).get(
                "content"
            ) or ""
            return model, "OK", time.time() - t0, (txt or "")[:40].replace("\n", " ")
    except Exception as e:  # noqa: BLE001 — probe must classify all failures
        detail = str(e)
        status = "FAIL"
        if isinstance(e, urllib.error.HTTPError):
            status = f"FAIL_{e.code}"
            try:
                b = e.read().decode()
                detail = b[:160].replace("\n", " ")
                if "Function" in b and "Not found" in b:
                    detail = "FUNCTION_NOT_FOUND"
            except Exception:
                pass
        elif "timed out" in detail.lower():
            detail = "TIMEOUT"
        return model, status, time.time() - t0, detail[:120]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--no-write", action="store_true")
    ap.add_argument("--allowlist", type=Path, default=DEFAULT_ALLOWLIST)
    ap.add_argument("--report", type=Path, default=None)
    args = ap.parse_args()

    key = os.environ.get("NVIDIA_API_KEY", "").strip()
    if not key:
        print("NVIDIA_API_KEY not set", file=sys.stderr)
        return 2

    ids = list_models(key)
    print(f"catalog_count={len(ids)}")

    ok: list[tuple[str, str, float, str]] = []
    fail: list[tuple[str, str, float, str]] = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as ex:
        for row in ex.map(lambda m: probe_chat(key, m), ids):
            if row[1] == "OK":
                ok.append(row)
            else:
                fail.append(row)

    print(f"invokable={len(ok)} failed={len(fail)}")
    for model, _st, secs, sample in sorted(ok, key=lambda r: r[0]):
        print(f"OK  {secs:5.1f}s  {model:55}  {sample!r}")

    reasons = Counter(r[3][:40] for r in fail)
    print("fail_reasons:")
    for k, v in reasons.most_common(12):
        print(f"  {v:3}  {k}")

    if not args.no_write:
        args.allowlist.parent.mkdir(parents=True, exist_ok=True)
        header = (
            "# NVIDIA NIM invokable chat models (auto-generated by scripts/probe-nim-catalog.py)\n"
            f"# Generated: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n"
            f"# Catalog={len(ids)} invokable={len(ok)} failed={len(fail)}\n"
            "# Re-run: NVIDIA_API_KEY=… python3 scripts/probe-nim-catalog.py\n\n"
        )
        body = "\n".join(m for m, *_ in sorted(ok, key=lambda r: r[0])) + "\n"
        args.allowlist.write_text(header + body)
        print(f"wrote {args.allowlist}")

    if args.report:
        lines = [
            "# NVIDIA NIM catalog probe\n",
            f"\nCatalog: {len(ids)} · Invokable: {len(ok)} · Failed: {len(fail)}\n",
            "\n## Invokable\n\n| Model | s | sample |\n|---|---:|---|\n",
        ]
        for model, _st, secs, sample in sorted(ok, key=lambda r: r[0]):
            lines.append(f"| `{model}` | {secs:.2f} | {sample!r} |\n")
        lines.append("\n## Failed\n\n| Model | status | detail |\n|---|---|---|\n")
        for model, st, _secs, detail in sorted(fail, key=lambda r: r[0]):
            d = detail[:100].replace("|", "/")
            lines.append(f"| `{model}` | {st} | {d} |\n")
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text("".join(lines))
        print(f"wrote {args.report}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
